### ISSUE TITLE
Remove usage of ?filter when querying the WP REST API

### ISSUE THREAD

**Issue by cjg89** [UCF/UCF-News-Plugin#5]
https://developer.wordpress.org/rest-api/using-the-rest-api/frequently-asked-questions/#what-happened-to-the-filter-query-parameter

**Comment by jmbarne3** [comment]
Because the `?filter` parameter is no longer available, we will either need to find an alternative for passing category and tag queries using slugs, or find a way to translate the slug args into IDs prior to sending or at the source (i.e. make an update to the today theme to use a custom query parameter).

**Comment by cjg89** [comment]
Resolved in #9.  Closing issue
